/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AArgListHelper extends PArgListHelper
{
    private PArgumentDecl _argumentDecl_;
    private TSemicolon _semicolon_;

    public AArgListHelper()
    {
        // Constructor
    }

    public AArgListHelper(
        @SuppressWarnings("hiding") PArgumentDecl _argumentDecl_,
        @SuppressWarnings("hiding") TSemicolon _semicolon_)
    {
        // Constructor
        setArgumentDecl(_argumentDecl_);

        setSemicolon(_semicolon_);

    }

    @Override
    public Object clone()
    {
        return new AArgListHelper(
            cloneNode(this._argumentDecl_),
            cloneNode(this._semicolon_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArgListHelper(this);
    }

    public PArgumentDecl getArgumentDecl()
    {
        return this._argumentDecl_;
    }

    public void setArgumentDecl(PArgumentDecl node)
    {
        if(this._argumentDecl_ != null)
        {
            this._argumentDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._argumentDecl_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._argumentDecl_)
            + toString(this._semicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._argumentDecl_ == child)
        {
            this._argumentDecl_ = null;
            return;
        }

        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._argumentDecl_ == oldChild)
        {
            setArgumentDecl((PArgumentDecl) newChild);
            return;
        }

        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
