/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import java.util.*;
import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AArrayExpressionLvl0 extends PExpressionLvl0
{
    private TIdentifier _identifier_;
    private final LinkedList<PExpressionHelper> _expressionHelper_ = new LinkedList<PExpressionHelper>();

    public AArrayExpressionLvl0()
    {
        // Constructor
    }

    public AArrayExpressionLvl0(
        @SuppressWarnings("hiding") TIdentifier _identifier_,
        @SuppressWarnings("hiding") List<?> _expressionHelper_)
    {
        // Constructor
        setIdentifier(_identifier_);

        setExpressionHelper(_expressionHelper_);

    }

    @Override
    public Object clone()
    {
        return new AArrayExpressionLvl0(
            cloneNode(this._identifier_),
            cloneList(this._expressionHelper_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrayExpressionLvl0(this);
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public LinkedList<PExpressionHelper> getExpressionHelper()
    {
        return this._expressionHelper_;
    }

    public void setExpressionHelper(List<?> list)
    {
        for(PExpressionHelper e : this._expressionHelper_)
        {
            e.parent(null);
        }
        this._expressionHelper_.clear();

        for(Object obj_e : list)
        {
            PExpressionHelper e = (PExpressionHelper) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._expressionHelper_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identifier_)
            + toString(this._expressionHelper_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._expressionHelper_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        for(ListIterator<PExpressionHelper> i = this._expressionHelper_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExpressionHelper) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
