/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AAsgnStatement extends PStatement
{
    private PAssignmentStmt _assignmentStmt_;

    public AAsgnStatement()
    {
        // Constructor
    }

    public AAsgnStatement(
        @SuppressWarnings("hiding") PAssignmentStmt _assignmentStmt_)
    {
        // Constructor
        setAssignmentStmt(_assignmentStmt_);

    }

    @Override
    public Object clone()
    {
        return new AAsgnStatement(
            cloneNode(this._assignmentStmt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAsgnStatement(this);
    }

    public PAssignmentStmt getAssignmentStmt()
    {
        return this._assignmentStmt_;
    }

    public void setAssignmentStmt(PAssignmentStmt node)
    {
        if(this._assignmentStmt_ != null)
        {
            this._assignmentStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assignmentStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._assignmentStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._assignmentStmt_ == child)
        {
            this._assignmentStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._assignmentStmt_ == oldChild)
        {
            setAssignmentStmt((PAssignmentStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
