/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AConcatExpressionLvlc extends PExpressionLvlc
{
    private PExpressionLvlc _expressionLvlc_;
    private TStrconcat _strconcat_;
    private PExpressionLvl3 _expressionLvl3_;

    public AConcatExpressionLvlc()
    {
        // Constructor
    }

    public AConcatExpressionLvlc(
        @SuppressWarnings("hiding") PExpressionLvlc _expressionLvlc_,
        @SuppressWarnings("hiding") TStrconcat _strconcat_,
        @SuppressWarnings("hiding") PExpressionLvl3 _expressionLvl3_)
    {
        // Constructor
        setExpressionLvlc(_expressionLvlc_);

        setStrconcat(_strconcat_);

        setExpressionLvl3(_expressionLvl3_);

    }

    @Override
    public Object clone()
    {
        return new AConcatExpressionLvlc(
            cloneNode(this._expressionLvlc_),
            cloneNode(this._strconcat_),
            cloneNode(this._expressionLvl3_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConcatExpressionLvlc(this);
    }

    public PExpressionLvlc getExpressionLvlc()
    {
        return this._expressionLvlc_;
    }

    public void setExpressionLvlc(PExpressionLvlc node)
    {
        if(this._expressionLvlc_ != null)
        {
            this._expressionLvlc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLvlc_ = node;
    }

    public TStrconcat getStrconcat()
    {
        return this._strconcat_;
    }

    public void setStrconcat(TStrconcat node)
    {
        if(this._strconcat_ != null)
        {
            this._strconcat_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._strconcat_ = node;
    }

    public PExpressionLvl3 getExpressionLvl3()
    {
        return this._expressionLvl3_;
    }

    public void setExpressionLvl3(PExpressionLvl3 node)
    {
        if(this._expressionLvl3_ != null)
        {
            this._expressionLvl3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLvl3_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressionLvlc_)
            + toString(this._strconcat_)
            + toString(this._expressionLvl3_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressionLvlc_ == child)
        {
            this._expressionLvlc_ = null;
            return;
        }

        if(this._strconcat_ == child)
        {
            this._strconcat_ = null;
            return;
        }

        if(this._expressionLvl3_ == child)
        {
            this._expressionLvl3_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressionLvlc_ == oldChild)
        {
            setExpressionLvlc((PExpressionLvlc) newChild);
            return;
        }

        if(this._strconcat_ == oldChild)
        {
            setStrconcat((TStrconcat) newChild);
            return;
        }

        if(this._expressionLvl3_ == oldChild)
        {
            setExpressionLvl3((PExpressionLvl3) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
