/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AEqExpressionLvl4 extends PExpressionLvl4
{
    private PExpressionLvlc _left_;
    private TEqual _equal_;
    private PExpressionLvlc _right_;

    public AEqExpressionLvl4()
    {
        // Constructor
    }

    public AEqExpressionLvl4(
        @SuppressWarnings("hiding") PExpressionLvlc _left_,
        @SuppressWarnings("hiding") TEqual _equal_,
        @SuppressWarnings("hiding") PExpressionLvlc _right_)
    {
        // Constructor
        setLeft(_left_);

        setEqual(_equal_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new AEqExpressionLvl4(
            cloneNode(this._left_),
            cloneNode(this._equal_),
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEqExpressionLvl4(this);
    }

    public PExpressionLvlc getLeft()
    {
        return this._left_;
    }

    public void setLeft(PExpressionLvlc node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public TEqual getEqual()
    {
        return this._equal_;
    }

    public void setEqual(TEqual node)
    {
        if(this._equal_ != null)
        {
            this._equal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equal_ = node;
    }

    public PExpressionLvlc getRight()
    {
        return this._right_;
    }

    public void setRight(PExpressionLvlc node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._equal_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._equal_ == child)
        {
            this._equal_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PExpressionLvlc) newChild);
            return;
        }

        if(this._equal_ == oldChild)
        {
            setEqual((TEqual) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PExpressionLvlc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
