/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import java.util.*;
import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AExpressionList extends PExpressionList
{
    private final LinkedList<PExpressionListHelper> _expressionListHelper_ = new LinkedList<PExpressionListHelper>();
    private PExpression _expression_;

    public AExpressionList()
    {
        // Constructor
    }

    public AExpressionList(
        @SuppressWarnings("hiding") List<?> _expressionListHelper_,
        @SuppressWarnings("hiding") PExpression _expression_)
    {
        // Constructor
        setExpressionListHelper(_expressionListHelper_);

        setExpression(_expression_);

    }

    @Override
    public Object clone()
    {
        return new AExpressionList(
            cloneList(this._expressionListHelper_),
            cloneNode(this._expression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpressionList(this);
    }

    public LinkedList<PExpressionListHelper> getExpressionListHelper()
    {
        return this._expressionListHelper_;
    }

    public void setExpressionListHelper(List<?> list)
    {
        for(PExpressionListHelper e : this._expressionListHelper_)
        {
            e.parent(null);
        }
        this._expressionListHelper_.clear();

        for(Object obj_e : list)
        {
            PExpressionListHelper e = (PExpressionListHelper) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._expressionListHelper_.add(e);
        }
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressionListHelper_)
            + toString(this._expression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressionListHelper_.remove(child))
        {
            return;
        }

        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PExpressionListHelper> i = this._expressionListHelper_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExpressionListHelper) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
