/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AExpressionLvl0 extends PExpressionLvl0
{

    public AExpressionLvl0()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new AExpressionLvl0();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpressionLvl0(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
