/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import java.util.*;
import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AExprarrayExpressionLvl0 extends PExpressionLvl0
{
    private TIdentifier _identifier_;
    private PExpressionHelper _left_;
    private final LinkedList<PExpressionHelper> _right_ = new LinkedList<PExpressionHelper>();

    public AExprarrayExpressionLvl0()
    {
        // Constructor
    }

    public AExprarrayExpressionLvl0(
        @SuppressWarnings("hiding") TIdentifier _identifier_,
        @SuppressWarnings("hiding") PExpressionHelper _left_,
        @SuppressWarnings("hiding") List<?> _right_)
    {
        // Constructor
        setIdentifier(_identifier_);

        setLeft(_left_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new AExprarrayExpressionLvl0(
            cloneNode(this._identifier_),
            cloneNode(this._left_),
            cloneList(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprarrayExpressionLvl0(this);
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public PExpressionHelper getLeft()
    {
        return this._left_;
    }

    public void setLeft(PExpressionHelper node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public LinkedList<PExpressionHelper> getRight()
    {
        return this._right_;
    }

    public void setRight(List<?> list)
    {
        for(PExpressionHelper e : this._right_)
        {
            e.parent(null);
        }
        this._right_.clear();

        for(Object obj_e : list)
        {
            PExpressionHelper e = (PExpressionHelper) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._right_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identifier_)
            + toString(this._left_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._right_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        if(this._left_ == oldChild)
        {
            setLeft((PExpressionHelper) newChild);
            return;
        }

        for(ListIterator<PExpressionHelper> i = this._right_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExpressionHelper) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
