/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AGtExpressionLvl4 extends PExpressionLvl4
{
    private PExpressionLvlc _left_;
    private TGreaterEq _greaterEq_;
    private PExpressionLvlc _right_;

    public AGtExpressionLvl4()
    {
        // Constructor
    }

    public AGtExpressionLvl4(
        @SuppressWarnings("hiding") PExpressionLvlc _left_,
        @SuppressWarnings("hiding") TGreaterEq _greaterEq_,
        @SuppressWarnings("hiding") PExpressionLvlc _right_)
    {
        // Constructor
        setLeft(_left_);

        setGreaterEq(_greaterEq_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new AGtExpressionLvl4(
            cloneNode(this._left_),
            cloneNode(this._greaterEq_),
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGtExpressionLvl4(this);
    }

    public PExpressionLvlc getLeft()
    {
        return this._left_;
    }

    public void setLeft(PExpressionLvlc node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public TGreaterEq getGreaterEq()
    {
        return this._greaterEq_;
    }

    public void setGreaterEq(TGreaterEq node)
    {
        if(this._greaterEq_ != null)
        {
            this._greaterEq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._greaterEq_ = node;
    }

    public PExpressionLvlc getRight()
    {
        return this._right_;
    }

    public void setRight(PExpressionLvlc node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._greaterEq_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._greaterEq_ == child)
        {
            this._greaterEq_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PExpressionLvlc) newChild);
            return;
        }

        if(this._greaterEq_ == oldChild)
        {
            setGreaterEq((TGreaterEq) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PExpressionLvlc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
