/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AGteExpressionLvl4 extends PExpressionLvl4
{
    private PExpressionLvlc _left_;
    private TGreaterThan _greaterThan_;
    private PExpressionLvlc _right_;

    public AGteExpressionLvl4()
    {
        // Constructor
    }

    public AGteExpressionLvl4(
        @SuppressWarnings("hiding") PExpressionLvlc _left_,
        @SuppressWarnings("hiding") TGreaterThan _greaterThan_,
        @SuppressWarnings("hiding") PExpressionLvlc _right_)
    {
        // Constructor
        setLeft(_left_);

        setGreaterThan(_greaterThan_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new AGteExpressionLvl4(
            cloneNode(this._left_),
            cloneNode(this._greaterThan_),
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGteExpressionLvl4(this);
    }

    public PExpressionLvlc getLeft()
    {
        return this._left_;
    }

    public void setLeft(PExpressionLvlc node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public TGreaterThan getGreaterThan()
    {
        return this._greaterThan_;
    }

    public void setGreaterThan(TGreaterThan node)
    {
        if(this._greaterThan_ != null)
        {
            this._greaterThan_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._greaterThan_ = node;
    }

    public PExpressionLvlc getRight()
    {
        return this._right_;
    }

    public void setRight(PExpressionLvlc node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._greaterThan_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._greaterThan_ == child)
        {
            this._greaterThan_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PExpressionLvlc) newChild);
            return;
        }

        if(this._greaterThan_ == oldChild)
        {
            setGreaterThan((TGreaterThan) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PExpressionLvlc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
