/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import java.util.*;
import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AInnerClass extends PInnerClass
{
    private final LinkedList<TNewline> _newline_ = new LinkedList<TNewline>();
    private TClassKey _classKey_;

    public AInnerClass()
    {
        // Constructor
    }

    public AInnerClass(
        @SuppressWarnings("hiding") List<?> _newline_,
        @SuppressWarnings("hiding") TClassKey _classKey_)
    {
        // Constructor
        setNewline(_newline_);

        setClassKey(_classKey_);

    }

    @Override
    public Object clone()
    {
        return new AInnerClass(
            cloneList(this._newline_),
            cloneNode(this._classKey_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInnerClass(this);
    }

    public LinkedList<TNewline> getNewline()
    {
        return this._newline_;
    }

    public void setNewline(List<?> list)
    {
        for(TNewline e : this._newline_)
        {
            e.parent(null);
        }
        this._newline_.clear();

        for(Object obj_e : list)
        {
            TNewline e = (TNewline) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._newline_.add(e);
        }
    }

    public TClassKey getClassKey()
    {
        return this._classKey_;
    }

    public void setClassKey(TClassKey node)
    {
        if(this._classKey_ != null)
        {
            this._classKey_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._classKey_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._newline_)
            + toString(this._classKey_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._newline_.remove(child))
        {
            return;
        }

        if(this._classKey_ == child)
        {
            this._classKey_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<TNewline> i = this._newline_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TNewline) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._classKey_ == oldChild)
        {
            setClassKey((TClassKey) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
