/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AStringType extends PType
{
    private TStrIteral _strIteral_;

    public AStringType()
    {
        // Constructor
    }

    public AStringType(
        @SuppressWarnings("hiding") TStrIteral _strIteral_)
    {
        // Constructor
        setStrIteral(_strIteral_);

    }

    @Override
    public Object clone()
    {
        return new AStringType(
            cloneNode(this._strIteral_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStringType(this);
    }

    public TStrIteral getStrIteral()
    {
        return this._strIteral_;
    }

    public void setStrIteral(TStrIteral node)
    {
        if(this._strIteral_ != null)
        {
            this._strIteral_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._strIteral_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._strIteral_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._strIteral_ == child)
        {
            this._strIteral_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._strIteral_ == oldChild)
        {
            setStrIteral((TStrIteral) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
